### ISSUE TITLE
config.json missing

### ISSUE THREAD

**Issue by leandroamparo** [hebrewseniorlife/marcus_redcap_calendar_feed#1]
Hi, 
I have just downloaded your module to my redcap, but when I try to enable it, it show up like this: None (config.json is missing for marcus_redcap_calendar_feed), on the enable module pop-up and I'm not able to enable it.
thanks!
leandro.

**Comment by jasonrightmyer** [comment]
Checking on the build script.  We use a separate process internally to release to production.

**Comment by jasonrightmyer** [comment]
Build script is fine.  It appears that Vanderbilt's repository is downloading and expanding the wrong file or portion of the release.

**Comment by leandroamparo** [comment]
> 
> 
> Build script is fine. It appears that Vanderbilt's repository is downloading and expanding the wrong file or portion of the release.

thanks for the reply, I'll wait for the fix.

**Comment by jasonrightmyer** [comment]
Problem fixed.  The REDCap install routine is expecting a zip file with a single sub-folder containing the release. The build script and version have been updated.  See v1.3 for newest, working release.

**Comment by leandroamparo** [comment]
> 
> 
> Problem fixed. The REDCap install routine is expecting a zip file with a single sub-folder containing the release. The build script and version have been updated. See v1.3 for newest, working release.

thanks a lot!
